added security workflow

diff --git a/.github/workflows/pre-merge-checks.yaml b/.github/workflows/pre-merge-checks.yaml
--- a/.github/workflows/pre-merge-checks.yaml
+++ b/.github/workflows/pre-merge-checks.yaml
@@ -56,10 +56,6 @@ jobs:
         run: '.github/scripts/lint.sh'
         shell: bash
 
-      - name: Analyse templates
-        run: '.github/scripts/analyse.sh'
-        shell: bash
-
       - name: Lint Python
         uses: py-actions/flake8@v2
 
@@ -67,3 +63,29 @@ jobs:
         uses: ludeeus/action-shellcheck@master
         env:
           SHELLCHECK_OPTS: --shell=bash --external-sources
+  
+  security-check:
+    permissions:
+      actions: read
+      contents: read
+      security-events: write
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
+      - name: Checkov GitHub Action
+        uses: bridgecrewio/checkov-action@v12
+        with:
+          # This will add both a CLI output to the console and create a results.sarif file
+          framework: cloudformation
+          quiet: true
+          output_format: cli,sarif
+          output_file_path: console,results.sarif
+
+      - name: Upload SARIF file
+        uses: github/codeql-action/upload-sarif@v2
+        # Results are generated only on a success or failure
+        # this is required since GitHub by default won't run the next step
+        # when the previous one has failed. Security checks that do not pass will 'fail'.
+        if: success() || failure()
+        with:
+          sarif_file: results.sarif
